# Generated by Django 3.1 on 2020-08-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200829_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='s_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='s_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='t_name',
        ),
    ]
